# @package _global_
# Config 2: Christiano et al. with expert Q-net oracle
preferences:
  oracle: "qnet"
  label_mode: "soft"
  use_demonstrations: false
  initial_prefs: 500
  segment_len: 25
  max_segs: 1000
  db_train_maxlen: 3000
  db_val_maxlen: 750
  seg_pipe_maxsize: 100
  demo_seg_pipe_maxsize: 100
  demo_db_maxlen: 1500
  disagreement_candidates: 20
  max_query_interval: 5.0
