run:
  seed: 0
  output_dir: outputs/demo_algorithm_v2

wandb:
  entity: andrea02polimi-politecnico-di-milano
  project: demo_v2
  tags: Null

env:
  id: "HighwayEgo-v0"
  n_envs: 4
  kwargs:
    ego: "continuous"
    reward: "fast"

agent:
  kwargs:
    policy: "MlpPolicy"
    n_steps: 1000
    n_epochs: 10
    learning_rate: 0.0003
    batch_size: 64
    ent_coef: 0
    gae_lambda: 0.95
    gamma: 0.997
    policy_kwargs:
      net_arch: [64, 64]
    device: "cpu"

algo:
  kwargs:
    lr_rew: 0.0001
    gradient_steps_rew: 100
    batch_size_expert: 32
    batch_size_model: 64
    reward_model_kwargs:
      net_arch: [32, 32]
      activation_fn: tanh

train:
  kwargs:
    total_timesteps: 2000000
    timesteps_per_iteration: 20000
    checkpoint_interval: 10

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
