"""
DemoAlgorithm: demonstration-based reward learning using MaxEnt IRL (Guided Cost Learning).

A fixed set of expert trajectories is passed at initialisation. At each
iteration the agent's current rollout is added to a fixed-size model buffer.
The reward model is updated by minimising the importance-weighted MaxEnt IRL loss:

    L = -mean(R_θ(τ^E)) + logsumexp(R_θ(τ^M) + log z_j) - log(M)

where z_j corrects for the fact that the buffered samples were generated by
several past policies. Following Finn et al. (2016, Sec. 4.3) we use the
*fusion* (mixture) distribution rather than per-sample importance weights:

    z_j = [ (1/W) Σ_κ q_κ(τ_j) ]^{-1}

i.e. each trajectory is weighted under the mixture of the last W policies. In
log-space, with log q_κ(τ) = Σ_t log π_κ(a_t | s_t):

    log z_j = log W - logsumexp_κ( log q_κ(τ_j) )

To keep the importance-sampling estimator consistent, the W policy snapshots and
the buffered rollouts live in coupled fixed-size windows (``policy_window``): the
mixture always covers exactly the policies that generated the buffer. Expert
demonstrations are weighted under the same mixture (their true generating
distribution is unknown; this is the chosen approximation).
"""

import time
from collections import deque
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Callable, List, Optional, Union

import numpy as np
import torch as th
from scipy.special import logsumexp

from human_feedback_rl.common.base_reward_learning_algorithm import BaseRewardLearningAlgorithm
from human_feedback_rl.common.reward_nets import make_reward_ensemble
from human_feedback_rl.common.types import Trajectory


class DemoAlgorithm(BaseRewardLearningAlgorithm):
    """
    Demonstration-based reward learning via MaxEnt IRL.

    Expert trajectories are passed once at initialisation and stay fixed for
    the entire training run.  At each iteration the algorithm:

      1. Collects agent trajectories via rollout (self.trajectories).
      2. Attaches importance weights log z_j = -log q_κ(τ_j) to each trajectory.
      3. Appends the rollout to a cumulative model buffer (self._model_buffer).
      4. Updates the reward model with the importance-weighted loss:
            L = -mean(R_θ(τ^E)) + logsumexp(R_θ(τ^M) + log z_j) - log(M)
      5. Trains the agent with the updated reward model.
    """

    def __init__(
        self,
        env,
        agent,
        expert_trajectories: List[Trajectory],
        lr_rew: float = 0.001,
        gradient_steps_rew: int = 10,
        batch_size_expert: int = 32,
        batch_size_model: int = 64,
        l2_rew: float = 0.01,
        fragment_length: int = 1,
        temperature: float = 1,
        initial_queries: int = 0,
        exploration_frac: float = 0.0,
        exploration_eps: float = 0.5,
        query_schedule: Union[str, Callable[[float], float]] = "constant",
        policy_window: int = 10,
        importance_weighting: bool = True,
        reward_model_kwargs: Optional[dict] = None,
        reward_model_factory: Callable = make_reward_ensemble,
        grad_clip_rew: Optional[float] = None,
        rng: Optional[np.random.Generator] = None,
        log_folder: Optional[str] = None,
        output_formats: Optional[List] = None,
        debug_dataset: Optional[dict] = None,
    ):
        if not expert_trajectories:
            raise ValueError("expert_trajectories must be a non-empty list of Trajectory objects.")

        reward_model = reward_model_factory(env, **(reward_model_kwargs or {}))

        super().__init__(
            env=env,
            agent=agent,
            reward_model=reward_model,
            train_comparison_frac=1.0,
            fragment_length=fragment_length,
            initial_queries=initial_queries,
            exploration_frac=exploration_frac,
            exploration_eps=exploration_eps,
            query_schedule=query_schedule,
            temperature=temperature,
            rng=rng,
            log_folder=log_folder,
            output_formats=output_formats,
            debug_dataset=debug_dataset,
        )

        self.expert_trajectories      = list(expert_trajectories)
        self.gradient_steps_rew       = gradient_steps_rew
        self.batch_size_expert        = batch_size_expert
        self.batch_size_model         = batch_size_model
        self.grad_clip_rew            = grad_clip_rew
        self.policy_window_size       = policy_window
        # Ablation switch: when False, the fusion importance weights are forced to
        # uniform (log_iw = 0 for every trajectory), i.e. the MaxEnt partition
        # function is estimated as a plain mean over the buffer. Use this to
        # isolate the reward-learning signal from the (often degenerate)
        # importance-sampling estimator.
        self.importance_weighting     = importance_weighting

        # Coupled fixed-size windows over the last `policy_window` iterations:
        #   _model_buffer  – one list of trajectories per iteration
        #   _policy_window – a frozen snapshot of the policy that generated it
        # Fusion importance weights are computed over exactly these policies, so
        # the IS estimator stays consistent. Both deques evict in lock-step.
        self._model_buffer: "deque[List[Trajectory]]" = deque(maxlen=policy_window)
        self._policy_window: deque = deque(maxlen=policy_window)

        # Fixed validation snapshot (expert + model trajectories) captured on the
        # first evaluation and reused for a deterministic, comparable loss_val.
        self._eval_snapshot: Optional[tuple] = None

        self.optimizers = [
            th.optim.Adam(m.parameters(), lr=lr_rew, weight_decay=l2_rew)
            for m in self.reward_model.members
        ]

    # ------------------------------------------------------------------
    # Abstract hook implementations
    # ------------------------------------------------------------------

    def collect_feedback(self, _num_queries: int):
        """No feedback collection needed; expert data is fixed at init."""
        return [], []

    def push_data(self, _fragments, _feedback) -> None:
        """Accumulate the current rollout and refresh fusion importance weights.

        Called after sample_rollout() but before train_agent(), so the policy is
        still π_κ — the one that generated self.trajectories this iteration. The
        rollout batch and a snapshot of π_κ enter coupled fixed-size windows, so
        the fusion mixture always covers exactly the policies that produced the
        buffered samples.
        """
        self._model_buffer.append(list(self.trajectories))
        self._update_importance_weights()
        self.logger.record("dataset/expert_size",   len(self.expert_trajectories))
        self.logger.record("dataset/model_size",    sum(len(b) for b in self._model_buffer))
        self.logger.record("dataset/policy_window", len(self._policy_window))

    def train_reward_model(self) -> None:
        """MaxEnt IRL reward model update using the cumulative model buffer."""
        if not self._model_buffer:
            return

        t0 = time.perf_counter()

        def train_member(member, optimizer):
            member.train()
            for _ in range(self.gradient_steps_rew):
                loss = self._compute_reward_loss(member)
                optimizer.zero_grad()
                loss.backward()
                if self.grad_clip_rew is not None:
                    th.nn.utils.clip_grad_norm_(member.parameters(), self.grad_clip_rew)
                optimizer.step()

        with ThreadPoolExecutor(max_workers=1) as executor:
            futures = [
                executor.submit(train_member, member, optimizer)
                for member, optimizer in zip(self.reward_model.members, self.optimizers)
            ]
            for future in as_completed(futures):
                future.result()

        t_train = time.perf_counter() - t0

        t0 = time.perf_counter()
        loss_val = self._evaluate_reward_model()
        self.logger.record("reward/loss_val",         loss_val, exclude="stdout")
        self.logger.record("time/train_reward_model", t_train)
        self.logger.record_sum("time/loggings",       time.perf_counter() - t0)

    def _compute_reward_loss(self, member, eval_batch=None) -> th.Tensor:
        """Loss used for reward model training. Override in subclasses.

        When ``eval_batch`` is provided (a ``(expert_trajs, model_trajs)`` tuple),
        the loss is computed on that fixed batch instead of resampling — used by
        ``_evaluate_reward_model`` to keep the validation loss deterministic.
        """
        if eval_batch is None:
            eval_batch = self._sample_loss_batch()
        return self._maxent_loss_on(member, *eval_batch)

    def _evaluate_reward_model(self) -> float:
        """Reward-model loss on a fixed validation snapshot.

        The snapshot (a subset of expert and model trajectories with their
        importance weights) is sampled once on the first call and reused for every
        subsequent evaluation. This keeps ``loss_val`` deterministic and comparable
        across iterations: resampling fresh random batches — as the training loss
        does — would make the metric noisy and shift it by a different importance-
        weight centering constant on each call.
        """
        if not self._model_buffer:
            return float("nan")

        if self._eval_snapshot is None:
            self._eval_snapshot = self._sample_loss_batch()

        self.reward_model.eval()
        with th.no_grad():
            components = [
                self._maxent_components_on(m, *self._eval_snapshot)
                for m in self.reward_model.members
            ]
        self.reward_model.train()

        def _avg(key):
            return float(np.mean([c[key].item() for c in components]))

        expert_return = _avg("expert_return")
        model_return  = _avg("model_return")
        # The expert-model return gap is the actual IRL separation signal: if it
        # collapses toward 0 the reward can no longer distinguish demos from the
        # agent (the classic GCL failure), regardless of the total loss value.
        self.logger.record("reward/expert_return", expert_return, exclude="stdout")
        self.logger.record("reward/model_return",  model_return,  exclude="stdout")
        self.logger.record("reward/return_gap",    expert_return - model_return, exclude="stdout")
        self.logger.record("reward/log_z",         _avg("log_z"), exclude="stdout")
        return _avg("loss")

    def before_agent_training(self) -> None:
        """Normalize the reward model mean across current agent transitions."""
        all_transitions = [t for traj in self.trajectories for t in traj]
        if not all_transitions:
            return
        obs    = np.array([t.observation for t in all_transitions])
        acts   = np.array([t.action      for t in all_transitions])
        status = np.array([t.next_status for t in all_transitions])
        done   = np.array([float(t.done) for t in all_transitions])

        for member in self.reward_model.members:
            raw = member.predict_unnormalized(obs, acts, status, done)
            member.set_mean(raw.mean())

        raw = self.reward_model.predict_unnormalized(obs, acts, status, done)
        self.reward_model.set_mean(raw.mean())

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _buffer_trajectories(self) -> List[Trajectory]:
        """Flatten the windowed model buffer into a single list of trajectories."""
        return [traj for batch in self._model_buffer for traj in batch]

    def _update_importance_weights(self) -> None:
        """Snapshot the current policy and recompute the fusion importance weights.

        Called from push_data while the policy is still π_κ (the one that generated
        this iteration's rollout). Algorithms whose reward loss does not use
        importance weights (e.g. GAIL/AIRL) override this as a no-op.
        """
        # Snapshots are only needed for the fusion IS estimate; skip them (and the
        # per-iteration state_dict copy) when running the uniform-weight ablation.
        if self.importance_weighting:
            self._policy_window.append(self._snapshot_policy())
        self._recompute_fusion_weights()

    def _snapshot_policy(self):
        """Frozen snapshot of the current policy weights, for off-policy log-prob eval.

        We store a detached CPU copy of the ``state_dict`` rather than
        ``deepcopy``-ing the live ``nn.Module``: SB3 policies cache an
        ``action_dist`` holding non-leaf tensors from the last forward pass,
        which ``copy.deepcopy`` cannot copy. Snapshots are evaluated later by
        loading them into the live policy (see ``_recompute_fusion_weights``).
        """
        policy = self.trajectory_generator.agent.policy
        return {k: v.detach().cpu().clone() for k, v in policy.state_dict().items()}

    @staticmethod
    def _load_snapshot(policy, snapshot):
        """Load a snapshot state_dict into `policy` and return it (for chaining)."""
        policy.load_state_dict(snapshot)
        return policy

    def _trajectory_logprobs_under(self, policy, trajectories: List[Trajectory]) -> np.ndarray:
        """Return Σ_t log π(a_t | s_t) for each trajectory under `policy` (no grad).

        All transitions are batched into a single forward pass and then segment-
        summed back per trajectory.
        """
        lengths = [len(traj) for traj in trajectories]
        obs  = np.concatenate([np.array([t.observation for t in traj]) for traj in trajectories])
        acts = np.concatenate([np.array([t.action      for t in traj]) for traj in trajectories])
        with th.no_grad():
            _, log_prob, _ = policy.evaluate_actions(
                th.as_tensor(obs,  dtype=th.float32),
                th.as_tensor(acts, dtype=th.float32),
            )
        log_prob = log_prob.cpu().numpy()

        sums  = np.empty(len(trajectories), dtype=np.float64)
        start = 0
        for i, length in enumerate(lengths):
            sums[i] = log_prob[start:start + length].sum()
            start += length
        return sums

    def _recompute_fusion_weights(self) -> None:
        """Set traj.log_importance_weight = -log p_mix(τ) over the current window.

        p_mix(τ) = (1/W) Σ_{κ∈window} q_κ(τ) is the fusion distribution of the W
        policies that generated the buffered rollouts (Finn et al. 2016, Sec. 4.3),
        so  log_iw = log W - logsumexp_κ( Σ_t log π_κ(a_t | s_t) ).

        Importance weights do not depend on the reward parameters θ, so they are
        recomputed once per iteration here and reused across all gradient steps.
        Expert demonstrations are weighted under the same mixture.
        """
        trajectories = self._buffer_trajectories() + self.expert_trajectories

        # Ablation: force uniform weights (log_iw = 0), turning the partition
        # function into a plain mean over the buffer. Skips the (expensive and,
        # in continuous control, often degenerate) full-trajectory IS estimate.
        # No policy snapshots are taken in this mode, so the window is empty.
        if not self.importance_weighting:
            for traj in trajectories:
                traj.log_importance_weight = 0.0
            self.logger.record("fusion/importance_weighting", 0, exclude="stdout")
            return

        window = list(self._policy_window)
        if not window:
            return

        # Each snapshot is a state_dict; evaluate it by loading into the live
        # policy, then restore the live weights afterwards.
        policy = self.trajectory_generator.agent.policy
        live_state = {k: v.detach().clone() for k, v in policy.state_dict().items()}
        was_training = policy.training
        policy.set_training_mode(False)
        try:
            logq = np.stack(
                [
                    self._trajectory_logprobs_under(
                        self._load_snapshot(policy, snapshot), trajectories
                    )
                    for snapshot in window
                ],
                axis=0,
            )  # [W, n_traj]
        finally:
            policy.load_state_dict(live_state)
            policy.set_training_mode(was_training)

        log_iw = np.log(len(window)) - logsumexp(logq, axis=0)
        for traj, weight in zip(trajectories, log_iw):
            traj.log_importance_weight = float(weight)

        # Effective sample size of the fusion weights over the buffered model
        # trajectories. ESS << n_model means the mixture is degenerate (one
        # trajectory dominates the partition sum) — a leading cause of GCL
        # collapse, distinct from the reward simply over/under-fitting.
        n_model = len(self._buffer_trajectories())
        if n_model:
            w = np.exp(log_iw[:n_model] - log_iw[:n_model].max())
            ess = float(w.sum() ** 2 / np.sum(w ** 2))
            self.logger.record("fusion/ess",          ess,          exclude="stdout")
            self.logger.record("fusion/ess_frac",     ess / n_model, exclude="stdout")
            self.logger.record("fusion/log_iw_std",   float(log_iw[:n_model].std()), exclude="stdout")

    def _traj_sum_reward(self, member, traj: Trajectory) -> th.Tensor:
        """Sum of per-step rewards over a trajectory (supports gradients)."""
        obs         = th.tensor(np.array([t.observation  for t in traj]), dtype=th.float32)
        actions     = th.tensor(np.array([t.action       for t in traj]), dtype=th.float32)
        next_status = th.tensor(np.array([t.next_status  for t in traj]), dtype=th.float32)
        done        = th.tensor(np.array([float(t.done)  for t in traj]), dtype=th.float32)
        return member(obs, actions, next_status, done).sum()

    def _sample_loss_batch(self):
        """Sample a ``(expert_trajs, model_trajs)`` mini-batch for the MaxEnt loss."""
        n_e     = min(self.batch_size_expert, len(self.expert_trajectories))
        exp_idx = self.rng.choice(len(self.expert_trajectories), size=n_e, replace=False)
        selected_expert = [self.expert_trajectories[i] for i in exp_idx]

        model_trajectories = self._buffer_trajectories()
        n_m       = min(self.batch_size_model, len(model_trajectories))
        model_idx = self.rng.choice(len(model_trajectories), size=n_m, replace=False)
        selected_model = [model_trajectories[i] for i in model_idx]
        return selected_expert, selected_model

    def _maxent_components_on(self, member, selected_expert, selected_model) -> dict:
        """Decomposed importance-weighted MaxEnt IRL loss for one member.

        Algorithm 2 (Finn et al. 2016):
          - First term : -mean(R_θ(τ^E))              [push reward up on demos]
          - Second term: logsumexp over model + demo   [partition function Z]

        The demo mini-batch is appended to the model mini-batch in the logsumexp
        (Algorithm 2 step 4). Without it the objective can become unbounded.
        Importance weights log z_j = -log q_κ(τ_j) are precomputed in push_data.

        Returns the loss together with its components (expert term, partition
        term, expert/model mean returns) so callers can log the decomposition.
        """
        # Expert mini-batch — same batch used in both terms (Algorithm 2, step 4).
        n_e = len(selected_expert)
        expert_returns = th.stack([
            self._traj_sum_reward(member, traj) for traj in selected_expert
        ])
        log_iw_expert = th.tensor(
            [traj.log_importance_weight for traj in selected_expert], dtype=th.float32
        )

        # Model mini-batch from the cumulative buffer.
        n_m = len(selected_model)
        model_returns = th.stack([
            self._traj_sum_reward(member, traj) for traj in selected_model
        ])
        log_iw_model = th.tensor(
            [traj.log_importance_weight for traj in selected_model], dtype=th.float32
        )

        # Append demo batch to model batch for the partition function estimate.
        all_returns = th.cat([model_returns, expert_returns])
        all_log_iw  = th.cat([log_iw_model,  log_iw_expert])
        n_total     = n_m + n_e

        # Centre log_iw before logsumexp: subtracting the mean is a constant
        # w.r.t. θ (IW depend on the policy, not the reward model), so the
        # gradient is identical but the computation is numerically stable.
        all_log_iw = all_log_iw - all_log_iw.mean()

        log_z = th.logsumexp(all_returns + all_log_iw, dim=0) - np.log(n_total)

        expert_mean = expert_returns.mean()
        return {
            "loss":          -expert_mean + log_z,
            "log_z":         log_z,
            "expert_return": expert_mean,
            "model_return":  model_returns.mean(),
        }

    def _maxent_loss_on(self, member, selected_expert, selected_model) -> th.Tensor:
        """Importance-weighted MaxEnt IRL loss for one member on a given mini-batch."""
        return self._maxent_components_on(member, selected_expert, selected_model)["loss"]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def train(
        self,
        total_timesteps: int = 1_000_000,
        total_queries: int = 10_000,
        timesteps_per_iteration: int = 1024,
        log_interval: int = 1,
        checkpoint_dir: Optional[str] = None,
        checkpoint_interval: int = 10,
    ) -> Any:
        return super().train(
            total_timesteps=total_timesteps,
            total_queries=total_queries,
            timesteps_per_iteration=timesteps_per_iteration,
            log_interval=log_interval,
            checkpoint_dir=checkpoint_dir,
            checkpoint_interval=checkpoint_interval,
        )
