env:
  expert_model: "2026-03-09_17-15-41_train_highway_fast_DQN/model"

agent:
  model: "scripts/models/policy_rlhf.pt"

eval:
  mode: side_by_side   # agent | expert | side_by_side
  episodes: 20
  deterministic: true

hydra:
  run:
    dir: experiments/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: config