run:
  # Path to the training run directory (relative to human-feedback-rl/)
  dir: "experiments/christiano/2026-03-17/11-50-32"

agent:
  # Path to the policy checkpoint (relative to human-feedback-rl/)
  model: "experiments/christiano/2026-03-17/11-50-32/models/policy_christiano"

eval:
  episodes: 100

hydra:
  run:
    dir: experiments/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: config
