seed: 0

run:

  # directory del run da valutare
  dir: experiments/runs/2026-03-11/11-47-18

agent:

  # modello da valutare (relativo alla root del progetto)
  model: models/policy_bc.pt

eval:

  episodes: 100


hydra:

  run:
    dir: experiments/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}

  output_subdir: config